### ISSUE TITLE
Use locally installed `oc` binary if its available

### ISSUE THREAD

**Issue by ifireball** [CentOS-PaaS-SIG/contra-env-setup#102]
When working with a remote OpenShift cluster, the playbook always installs the `oc` binary in its own. It desirable the use the locally installed one if its available in $PATH to save some time.

**Comment by arilivigni** [comment]
Not sure I really see the need to do that.  More of a nit than anything

**Comment by ifireball** [comment]
Well, it takes ~30-60 seconds to download it every time on my machine, it its really an itch I want to scratch.
