### ISSUE TITLE
set run_prereqs=false and setup_minishift=false by default

### ISSUE THREAD

**Issue by ifireball** [CentOS-PaaS-SIG/contra-env-setup#103]
These are destructive operations and are of no interest if one does not intend to run things locally. 
The default should be to switch then off IMO.

**Comment by arilivigni** [comment]
The typical default use is with minishift so we want that to be the default.  Also you can provide a file with pre-reqs for an OpenShift cluster which should be the way to use this.  This is  how CVP does it.
