### ISSUE TITLE
Make code more secure when using remote clusters

### ISSUE THREAD

**Issue by ifireball** [CentOS-PaaS-SIG/contra-env-setup#104]
Right now when using remote OpenShift clusters the code here will by default:
1. Disable all TLS checking
2. Require one to specify the OpenShift username and password on the command line

We should:
1. Enable TLS checking by default and have a parameter to disable it
2. Enable using a token instead of a password
3. Enable assuming the local user had already logged into the OpenShift cluster.

**Comment by arilivigni** [comment]
Maybe a nice to have not really critical

**Comment by arilivigni** [comment]
This fix was merged
