### ISSUE TITLE
Don't do `git config --global http.sslVerify false`

### ISSUE THREAD

**Issue by psiroky** [CentOS-PaaS-SIG/contra-env-setup#110]
The setup currently _globally_ disables git SSL verification with `git config --global http.sslVerify false`. That is potentially dangerous as users may not expect this being setup globally (at least I wasn't expecting that). Perhaps just setting this per repo would be be enough?

**Comment by gsaslis** [comment]
+1

**Comment by dirgim** [comment]
Addressed with #157 by resetting the global http.sslVerify configuration back to what it was before the setup.
