### ISSUE TITLE
Fail if prerequisites are missing but installation is skipped

### ISSUE THREAD

**Issue by ifireball** [CentOS-PaaS-SIG/contra-env-setup#111]
The `run_prereqs` variable allows one to skip the installation of prerequisites on the machine Ansible is running from. This is useful when one is using the playbook for managing a remote OpenShift instance and does not desire to grant the playbook root access to the local machine.

When prerequisites are missing it can result in strange and unexpected outcomes, for example if the `jq` command is missing, the playbook would finis successfully, but various commands it triggered would have not properly done what they needed to do.

It is desirable to make sure the playbook fails predictably if prerequisites are missing to avoid unexpected results

**Comment by dirgim** [comment]
The installation of `jq` was addressed with #119 and #143, while the other missing prerequisites fail reliably on either the minishift start steps or the git cloning steps.
