### ISSUE TITLE
Namespace definitions in templates are not set via the variable

### ISSUE THREAD

**Issue by ifireball** [CentOS-PaaS-SIG/contra-env-setup#113]
The variable `openshift_project` is used to determine which Kubernetes namespace are we installing things into. 

That information is, however, not being passed along when instantiating OpenShift templates to create the various object that are being created.

As a result, the created objects may end up referring to the wrong or even non-existent namespaces. For example the Jenkins deployment can end up being configured to trigger on changed to the `jenkins` image stream in the ` contra-sample-project` namespace (The default value for the NAMESPACE parameter) as opposed to the image stream that was actually created by by the playbook.

It is theoretically possible to customize the parameters being passed to the template, but merging PR #112 is required to allow that in practice  and it may be very cumbersome to do customization in practice as one needs to specify all the relevant template parameters when customizing, as opposed to jest the ones that need to be customized.

**Comment by arilivigni** [comment]
We handled only certain parameters to templates.  Does your solution address any build_parameter the ability to over write them?  If so I welcome that fix for all templates.

**Comment by ifireball** [comment]
I don`t have a solution yet; This is indeed not easy to solve in a non-kludgy way.
