### ISSUE TITLE
Add an example for remote configuration to README

### ISSUE THREAD

**Issue by ifireball** [CentOS-PaaS-SIG/contra-env-setup#114]
The README currenty only includes examples of using minishift locally, since deploying to a remote OpenShift cluster is a supported use case, we should include an example in the README for how to do that.

**Comment by arilivigni** [comment]
Feel free to update the README with examples we welcome PRs

**Comment by arilivigni** [comment]
Fix: https://github.com/CentOS-PaaS-SIG/contra-env-setup/pull/116
