### ISSUE TITLE
Didn't insert into '~/.bashrc' the path to 'oc' and 'minishift'

### ISSUE THREAD

**Issue by firemanxbr** [CentOS-PaaS-SIG/contra-env-setup#41]
I ran the command below:

$ ansible-playbook -i "localhost," contra-env-setup/playbooks/setup.yml     --vault-password-file=pipeline/config/password.txt --connection=local -K -e @pipeline/config/contra-env-setup.yml -e BASE64_ANSIBLE_VAULT_PASSWORD="$(cat pipeline/config/password.txt | base64 )" -e @pipeline/config/ansible/vault.yml -e user=$USER --extra-vars='{"hooks": ["{{ project_dir }}/config/post_deployment_tasks.yml"]}'

The output of my ~/.bashrc:
$ cat ~/.bashrc
# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
        . /etc/bashrc
fi

**Comment by arilivigni** [comment]
It was removed by multiple people requests.  We don't want to modify people's path and she'll env.
