### ISSUE TITLE
We need to have the ansible-executor and linchpin-executor as part of the contra-env-setup

### ISSUE THREAD

**Issue by arilivigni** [CentOS-PaaS-SIG/contra-env-setup#43]
We have certain helper container images we use in minishift or OpenShift setup as part of the contra-env-setup.

- ansible-executor allows us to execute ansible playbooks/roles
- linchpin-executor allows us to provision resources in clouds and bare metal infrastructures.

@robnester-rh @scoheb make sense?

**Comment by robnester-rh** [comment]
If the intention is to have public to the contra-env-setup on github, then yes, I think the only workable solution would be to build an upstream linchpin container and have internal specific aspects built on top of that.

**Comment by arilivigni** [comment]
@robnester-rh I think I am going to add an upstream version of the linchpin container for now.  If we need beaker we can have a version that includes those requirements internally.  Long-term we will have a linchpin container on dockerhub as a base container for the internal one.  If that is an issue let me know.

**Comment by robnester-rh** [comment]
@arilivigni - I think that solution will work fine.

**Comment by arilivigni** [comment]
https://github.com/CentOS-PaaS-SIG/contra-env-setup/pull/44

**Comment by firemanxbr** [comment]
we can close this issue, fixed on #44 @arilivigni

**Comment by arilivigni** [comment]
Fixed as of v1.1.2
