### ISSUE TITLE
Upgrade Minishift CentOS image

### ISSUE THREAD

**Issue by psiroky** [CentOS-PaaS-SIG/contra-env-setup#54]
Minishift v1.13.0+ no longer works with the current custom CentOS image. We need at a fix for https://github.com/minishift/minishift-centos-iso/issues/216. In CVP I've tested with https://github.com/minishift/minishift-centos-iso/releases/download/v1.10.0/minishift-centos7.iso and so far everything works as expected.

**Comment by arilivigni** [comment]
ISO has been updated to support Minishift v1.17.0
