### ISSUE TITLE
Cleanup of failed builds doesn't remove all the created resources

### ISSUE THREAD

**Issue by dirgim** [CentOS-PaaS-SIG/contra-env-setup#58]
Right now, when a build fails, only the bc, dc, routes, imagestreams, serviceaccounts, pvc, and rolebindings bearing the name of the app are deleted. If anything other than those is defined in the loaded template( e.g. configmaps, secrets, etc.), it won't be deleted and the next build retry with the _new-app_ command will break the playbook as it attempts to create resources that already exist.

Since there is no guarantee that the resources will have name related to the app or the build, I have two ideas for solving this:
- Creating the app and starting the build with the _new-app_ command only once (on the first build attempt) with subsequent retries just restarting the builds and using the already created resources
- Storing the output of the _new-app_ command in a hash for every specific template (or app) and using the information within it to delete all resources it created if a build fails

**Comment by arilivigni** [comment]
@dirgim all you have to do is add the other commands as resources as part of the cleanup.  As of now we covered everything for Jenkins so what templates are leaving things behind.  If you don't have to commands I can send them to you.

**Comment by dirgim** [comment]
I may have missed something, but I tried adding the _secret_ and _configmap_ resource types to the items to be checked in the cleanup task and it would still just grep for the app name (extracted from the failed build name) among those resources and miss any resources that had a different name.

**Comment by arilivigni** [comment]
I don't think you can do it by app name if this isn't blocking lets discuss on Monday I am on PTO today.

Quick example but probably needs to be tweaked:
for var in configmaps po rolebindings deploymentconfigs svc pvc routes imagestreams buildconfigs serviceaccounts secrets; do ~/.minishift/cache/oc/v3.9.0/linux/oc get $var | egrep -v 'NAME|sa|^default|^builder|^deployer|^system|^edit|^admin|^jenkins-dockercfg|^jenkins-token' | awk '{print $1}'| xargs -i echo $var {}; done

**Comment by dirgim** [comment]
Sure, it's not blocking, just something I ran into while testing parallel builds

**Comment by dirgim** [comment]
Solved with #65
